<a href="https://colab.research.google.com/github/zulfiqarskd17/Basic-dataset-work-with-LR-algo/blob/main/Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('dataset.csv')
df.info()
df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Feature_1  100 non-null    float64
 1   Feature_2  100 non-null    int64
 2   Feature_3  100 non-null    float64
 3   Feature_4  100 non-null    float64
 4   Feature_5  100 non-null    int64
 5   Feature_6  100 non-null    float64
 6   Feature_7  100 non-null    float64
 7   Feature_8  100 non-null    int64
 8   Feature_9  100 non-null    float64
 9   Target     100 non-null    float64
dtypes: float64(7), int64(3)
memory usage: 7.9 KB

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Target
0,37.454012,31,0.091443,2.942389,0,1.895623,94.421129,7,0.734288,107.165537
1,95.071431,38,-3.655393,6.606014,0,8.222761,36.662455,4,3.249366,19.335290
2,73.199394,48,6.490867,1.768127,0,9.252532,81.429594,5,1.549414,90.074187
3,59.865848,31,-12.228735,1.465135,0,2.612083,3.416057,5,0.745921,151.232666
4,15.601864,3,5.363360,5.782192,0,3.321566,19.781193,2,1.884930,69.514305
5,15.599452,29,-9.146909,5.865716,0,7.810440,9.332409,6,2.518623,132.982345
6,5.808361,36,6.205482,6.736869,0,5.746130,99.062057,4,0.636623,159.089992
7,86.617615,22,-1.609374,7.534822,1,0.820638,86.246982,3,1.067333,185.435564
8,60.111501,38,-3.882644,9.782669,0,1.594313,0.408154,5,0.259958,46.928416
9,70.807258,44,-8.855124,5.646703,0,3.516429,13.676076,6,0.399707,79.863183

In [7]:
df.describe()

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Target
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,47.018074,24.400000,1.657547,5.329409,0.390000,3.889846,39.880987,5.090000,1.886677,99.619746
std,29.748941,14.760718,9.072760,2.657582,0.490207,2.685020,33.872229,2.353141,1.939109,60.664700
min,0.552212,0.000000,-17.884965,1.129541,0.000000,0.272478,0.038929,1.000000,0.047845,5.162381
25%,19.320076,10.750000,-4.675880,2.897322,0.000000,1.950709,8.194921,3.000000,0.531244,42.831253
50%,46.414245,27.000000,1.554423,5.476385,0.000000,3.243795,35.663055,5.000000,1.506120,99.952956
75%,73.020312,36.000000,8.720473,7.457228,1.000000,5.044953,68.748599,7.000000,2.362568,156.215642
max,98.688694,48.000000,27.344222,9.914546,1.000000,11.953171,99.996671,11.000000,10.278993,198.973263

In [8]:
df.isnull().sum()

Feature_1    0
Feature_2    0
Feature_3    0
Feature_4    0
Feature_5    0
Feature_6    0
Feature_7    0
Feature_8    0
Feature_9    0
Target       0
dtype: int64

In [9]:
df.duplicated().sum()

0

In [21]:
# prompt: drop target and put in y
x = df.drop('Target'  , axis=1)
y = df['Target']
x.head()

0    107.165537
1     19.335290
2     90.074187
3    151.232666
4     69.514305
Name: Target, dtype: float64

In [52]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(x , y , test_size=0.2 , random_state=42)

In [54]:
from sklearn.linear_model import LinearRegression

# Initialize the linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
y_pred

array([114.56622717, 110.94332481,  80.270609  , 149.2243586 ,
       109.64282106, 102.75977815,  96.30392088,  82.58572665,
       103.67166162, 118.11636422,  90.97383903,  82.92706121,
       117.11339121, 107.38605356,  92.2217918 , 106.43635967,
        99.60829654, 133.9555843 ,  98.64010429,  78.43884371])

In [51]:
y_test

83     30.404971
53     69.219945
70     27.033258
45    173.611338
44    175.594864
39     41.702103
22    141.748940
80     43.207637
10     30.483203
0     107.165537
18    151.054084
30     61.104862
73    193.164432
33    120.118867
90    139.007046
4      69.514305
76    101.228373
77     87.902338
12    185.400194
31     79.396303
Name: Target, dtype: float64